substitutions:
  _REGION: europe-north1
  _REPO: cloud-run-source-deploy
  _IMAGE: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/fagerhaug-vind

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_IMAGE}:${BUILD_ID}", "-t", "${_IMAGE}:latest", "."]

images:
  - ${_IMAGE}:${BUILD_ID}
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
